---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: $(event.pull_request.head.repo.html_url)
    - name: branch
      value: $(event.pull_request.head.ref)
    - name: origin
      value: $(event.pull_request.base.ref)
    - name: revision
      value: $(event.pull_request.head.sha)
