---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: statuses-url
      value: $(event.pull_request.statuses_url)
    - name: statuses-repo-url
      value: $(event.pull_request.base.repo.html_url)
    - name: repository
      value: $(event.pull_request.head.repo.html_url)
    - name: branch
      value: $(event.pull_request.head.ref)
    - name: origin
      value: $(event.pull_request.base.ref)
    - name: revision
      value: $(event.pull_request.head.sha)
    - name: base-commit
      value: $(event.pull_request.base.sha)
    - name: target-branch
      value: $(event.pull_request.base.ref)
    - name: pr-number
      value: $(event.pull_request.number)
