---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: branch
    - name: target-branch
      description: target branch
    - name: ibmcloud-api-key
      description: ibmcloud api key
    - name: statuses-url
      description: github statuses url
    - name: pipeline-debug

  workspaces:
    - name: artifacts

  tasks:
    - name: get-git-credentials
      taskRef:
        name: git-get-credentials
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: repository
          value: $(params.repository)
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)

    - name: clone-repo
      taskRef:
        name: git-clone
      runAfter:
        - get-git-credentials
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)

    - name: clone-common-tasks
      taskRef:
        name: git-clone
      runAfter:
        - get-git-credentials
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: repository
          value: "https://github.ibm.com/one-pipeline/common-tekton-tasks"
        - name: branch
          value: $(params.branch)
        - name: directory-name
          value: "common-tekton-tasks"

    - name: tekton-linter
      taskRef:
        name: tekton-lint
      runAfter:
        - clone-common-tasks
        - clone-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: definitions
          value: |
            compliance-cd-toolchain/.tekton/**/*.yaml
            common-tekton-tasks/preview/**/*.yaml
            common-tekton-tasks/preview/**/*.yml
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: statuses-url
          value: $(params.statuses-url)
