---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: save-git-token
spec:
  params:
    - name: pipeline-debug
      value: $(params.pipeline-debug)
      default: "0"

  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)

  steps:
    - name: save-git-token-to-file
      image: ibmcom/pipeline-base-image:2.6
      workingDir: "/artifacts"
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail

          if [ $PIPELINE_DEBUG == 1 ]; then
            pwd
            env
            trap env EXIT
            set -x
          fi

          source ./build.properties
          echo -n $GIT_TOKEN > ./github-token

  workspaces:
    - name: artifacts
      mountPath: /artifacts
