---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
      description: The git repo
      default: ""
    - name: origin
      description: origin to merge the code with
      default: ""
    - name: branch
      description: the branch for the git repo
    - name: revision
      description: |
        the git revision/commit to update the git HEAD to.
        Default is to mean only use the branch
      default: ""
    - name: statuses-repo-url
      description: the base repository's status URL
    - name: pipeline-debug
      default: "0"
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: target-branch
      description: target branch
    - name: pr-number
      description: the PR number
    - name: base-commit

  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce

    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson

    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
      metadata:
        name: sa-pullsecret

    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: repository
            value: $(params.repository)
          - name: origin
            value: $(params.origin)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: statuses-repo-url
            value: $(params.statuses-repo-url)
          - name: pr-number
            value: $(params.pr-number)
          - name: target-branch
            value: $(params.target-branch)
          - name: base-commit
            value: $(params.base-commit)
        serviceAccountName: sa-pullsecret
