---
inputs:
# - type: git
#   branch: master
#   service: ${TEKTON_CATALOG_REPO}
#   path: .tekton
- type: git
  branch: master
  service: ${TEKTON_DEFINITION_REPO}
  path: .tekton
triggers:
- type: manual
  name: Manual CD Trigger
  eventListener: listener
properties:
- name: repository
  value: ${REPOSITORY}
  type: text
- name: revision
  value: ${REVISION}
  type: text
- name: apikey
  value: ${API_KEY}
  type: SECURE
- name: registryNamespace
  value: ${REGISTRY_NAMESPACE}
  type: text 
- name: registryRegion
  value: ${REGISTRY_REGION_ID}
  type: text
- name: cluster
  value: ${PROD_CLUSTER_NAME}
  type: text 
- name: clusterNamespace
  value: ${PROD_CLUSTER_NAMESPACE}
  type: text
- name: clusterRegion
  value: ${PROD_REGION_ID}
  type: text
- name: serviceNowToken
  value: ${SERVICE_NOW_TOKEN}
  type: SECURE
- name: gheToken
  value: ${GHE_TOKEN}
  type: SECURE
- name: gheUser
  value: ${GHE_USER}
  type: text
- name: gheIssueRepo
  value: ${GHE_ISSUES_REPO}
  type: text
- name: evidenceLockerRepo
  value: ${EVIDENCE_LOCKER_REPO}
  type: text
- name: ghEmergencyLabel
  value: ${EMERGENCY_LABEL}
  type: text
- name: app
  value: ${CF_APP_NAME}
  type: text

