---
inputs:
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/git
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/servicenow
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/iks
  - type: git
    branch: master
    service: ${TEKTON_DEFINITION_REPO}
    path: .tekton
triggers:
  - type: manual
    name: Manual CD Trigger
    eventListener: cd-listener
properties:
  - name: repository
    value: ${REPOSITORY}
    type: text
  - name: revision
    value: ${BRANCH}
    type: text
  - name: ibmcloud-api-key
    value: ${API_KEY}
    type: SECURE
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: cluster
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: cluster-region
    value: ${PROD_REGION_ID}
    type: text
  - name: servicenow-api-token
    value: ${SERVICENOW_TOKEN}
    type: SECURE
  - name: servicenow-api-url
    value: ${SERVICENOW_URL}
    type: text
  - name: servicenow-configuration-item
    value: ${SERVICENOW_CONFIGURATION_ITEM}
    type: text
  - name: application
    value: ${APP_NAME}
    type: text
  - name: incident-issues-url
    value: ${INCIDENT_ISSUES_REPO}
    type: text
  - name: inventory-url
    value: ${INVENTORY_REPO}
    type: text
  - name: evidence-locker-url
    value: ${EVIDENCE_LOCKER_REPO}
    type: text
  - name: emergency-label
    value: ${EMERGENCY_LABEL}
    type: text
  - name: change-request-id
    value: ${CHANGEREQUEST_ID}
    type: text
