---
inputs:
- type: git
  branch: master
  service: ${TEKTON_CATALOG_REPO}
  path: preview/git
- type: git
  branch: master
  service: ${TEKTON_DEFINITION_REPO}
  path: .tekton
triggers:
- type: manual
  name: Manual CD Trigger
  eventListener: cd-listener
properties:
- name: repository
  value: ${REPOSITORY}
  type: text
- name: revision
  value: ${BRANCH}
  type: text
- name: ibmcloud-api-key
  value: ${API_KEY}
  type: SECURE
- name: registryNamespace
  value: ${REGISTRY_NAMESPACE}
  type: text 
- name: registryRegion
  value: ${REGISTRY_REGION_ID}
  type: text
- name: cluster
  value: ${PROD_CLUSTER_NAME}
  type: text 
- name: clusterNamespace
  value: ${PROD_CLUSTER_NAMESPACE}
  type: text
- name: clusterRegion
  value: ${PROD_REGION_ID}
  type: text
- name: serviceNowToken
  value: ${SERVICENOW_TOKEN}
  type: SECURE
- name: serviceNowUrl
  value: ${SERVICENOW_URL}
  type: text
- name: serviceNowConfigurationItem
  value: ${SERVICENOW_CONFIGURATION_ITEM}
  type: text
- name: app
  value: ${APP_NAME}
  type: text
- name: incidentIssueRepo
  value: ${INCIDENT_ISSUES_REPO}
  type: text
- name: evidenceLockerRepo
  value: ${EVIDENCE_LOCKER_REPO}
  type: text
- name: emergencyLabel
  value: ${EMERGENCY_LABEL}
  type: text
- name: changeRequestID
  value: ${CHANGEREQUEST_ID}
  type: text  
- name: image
  value: ${IMAGE_NAME}
  type: text  
