---
inputs:
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/git
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/inventory
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/servicenow
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/iks
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/toolchain
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/evidence
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/util
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/devops-insights
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/slack
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/github
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/compliance-checks
  - type: git
    branch: v1
    service: ${TEKTON_DEFINITION_REPO}
    path: .tekton
triggers:
  - type: git
    name: Git CD Trigger
    service: ${INVENTORY_REPO}
    branch: prod_candidate
    events:
      push: true
    eventListener: cd-listener
  - type: manual
    name: Manual CD Trigger
    eventListener: cd-listener
  - type: manual
    name: Manual Promotion Trigger
    eventListener: promotion-listener
properties:
  - name: revision
    value: ${BRANCH}
    type: text
  - name: ibmcloud-api-key
    value: ${API_KEY}
    type: SECURE
  - name: cluster
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: cluster-region
    value: ${PROD_REGION_ID}
    type: text
  - name: servicenow-api-token
    value: ${SERVICENOW_TOKEN}
    type: SECURE
  - name: servicenow-api-base-url
    value: ${SERVICENOW_BASE_URL}
    type: text
  - name: servicenow-configuration-item
    value: ${SERVICENOW_CONFIGURATION_ITEM}
    type: text
  - name: application
    value: ${APP_NAME}
    type: text
  - name: emergency-label
    value: ${EMERGENCY_LABEL}
    type: text
  - name: change-request-id
    value: ${CHANGEREQUEST_ID}
    type: text
  - name: artifactory-dockerconfigjson
    value: ${ARTIFACTORY_DOCKER_CONFIG_JSON}
    type: SECURE
  - name: pipeline-debug
    value: "0"
    type: text
  - name: version
    value: "v1"
    type: text
  - name: doi-toolchain-id
    value: ${DOI_TOOLCHAIN_ID}
    type: text
  - name: slack-notifications
    value: "0"
    type: text
  - name: cos-endpoint
    value: ${COS_ENDPOINT}
    type: text
  - name: cos-bucket-name
    value: ${COS_BUCKET_NAME}
    type: text
private_worker: ${PRIVATE_WORKER}
