---
inputs:
  - type: git
    branch: v8
    service: ${TEKTON_DEFINITION_REPO}
    path: .tekton
triggers:
  - type: git
    name: Git CD Trigger
    service: ${INVENTORY_REPO}
    branch: ${TARGET_ENVIRONMENT}
    disabled: true
    events:
      push: true
    eventListener: cd-listener
  - type: timer
    name: Git CD Timed Trigger
    eventListener: cd-listener
    disabled: ${GIT_CD_TIMED_TRIGGER_DISABLE}
    cron: "0 4 * * *"
  - type: manual
    name: Manual CD Trigger
    eventListener: cd-listener
  - type: manual
    name: Manual Promotion Trigger
    eventListener: promotion-listener
properties:
  - name: ibmcloud-api-key
    value: ${API_KEY}
    type: SECURE
  - name: cluster
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: cluster-region
    value: ${PROD_REGION_ID}
    type: text
  - name: servicenow-api-token
    value: ${SERVICENOW_TOKEN}
    type: SECURE
  - name: servicenow-api-base-url
    value: ${SERVICENOW_BASE_URL}
    type: text
  - name: servicenow-configuration-item
    value: ${SERVICENOW_CONFIGURATION_ITEM}
    type: text
  - name: emergency-label
    value: ${EMERGENCY_LABEL}
    type: text
  - name: source-environment
    value: ${SOURCE_ENVIRONMENT}
    type: text
  - name: target-environment
    value: ${TARGET_ENVIRONMENT}
    type: text
  - name: region
    value: ${REGION}
    type: text
  - name: doi-environment
    value: ${DOI_ENVIRONMENT}
    type: text
  - name: change-request-id
    value: notAvailable
    type: text
  - name: artifactory-dockerconfigjson
    value: ${ARTIFACTORY_DOCKER_CONFIG_JSON}
    type: SECURE
  - name: pipeline-debug
    type: single_select
    value:
      "0": true
      "1": false
  - name: version
    value: "v1"
    type: text
  - name: doi-toolchain-id
    value: ${DOI_TOOLCHAIN_ID}
    type: text
  - name: slack-notifications
    value: "1"
    type: text
  - name: cos-endpoint
    value: ${COS_ENDPOINT}
    type: text
  - name: cos-bucket-name
    value: ${COS_BUCKET_NAME}
    type: text
  - name: cos-api-key
    value: ${COS_API_KEY}
    type: SECURE
  - name: one-pipeline-config
    value: .one-pipeline.yaml
    type: text
  - name: one-pipeline-config-branch
    value: master
    type: text
  - name: git-token
    value: ""
    type: SECURE
  - name: inventory-repo
    value: inventory-repo
    type: INTEGRATION
    path: parameters.repo_url
  - name: evidence-repo
    value: evidence-locker-repo
    type: INTEGRATION
    path: parameters.repo_url
  - name: incident-repo
    value: incident-issues-repo
    type: INTEGRATION
    path: parameters.repo_url
