---
inputs:
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/inventory
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/servicenow-prepare-change-request/2.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/servicenow-create-change-request/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/servicenow-check-change-request-approval/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/servicenow-change-state-to-implement/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/servicenow-close-change-request/1.0.1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/iks
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/devops-insights
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/slack
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/github
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/compliance-collector/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/evidence-summarize/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/evidence-summary-format/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/evidence-summary-upload/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/pipeline-evaluate/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/git-clone/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/configmap/retry-command/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/toolchain-extract-value/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/git-get-credentials/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/compliance-doi-reporter/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/github-create-pull-request/1.0.0
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/condition/is-equal/1.0.0
  - type: git
    branch: develop
    service: ${TEKTON_DEFINITION_REPO}
    path: .tekton
triggers:
  - type: git
    name: Git CD Trigger
    service: ${INVENTORY_REPO}
    branch: prod_candidate
    events:
      push: true
    eventListener: cd-listener
  - type: manual
    name: Manual CD Trigger
    eventListener: cd-listener
  - type: manual
    name: Manual Promotion Trigger
    eventListener: promotion-listener
properties:
  - name: revision
    value: ${BRANCH}
    type: text
  - name: ibmcloud-api-key
    value: ${API_KEY}
    type: SECURE
  - name: cluster
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: cluster-region
    value: ${PROD_REGION_ID}
    type: text
  - name: servicenow-api-token
    value: ${SERVICENOW_TOKEN}
    type: SECURE
  - name: servicenow-api-base-url
    value: ${SERVICENOW_BASE_URL}
    type: text
  - name: servicenow-configuration-item
    value: ${SERVICENOW_CONFIGURATION_ITEM}
    type: text
  - name: application
    value: ${APP_NAME}
    type: text
  - name: emergency-label
    value: ${EMERGENCY_LABEL}
    type: text
  - name: change-request-id
    value: ${CHANGEREQUEST_ID}
    type: text
  - name: artifactory-dockerconfigjson
    value: ${ARTIFACTORY_DOCKER_CONFIG_JSON}
    type: SECURE
  - name: pipeline-debug
    value: "0"
    type: text
  - name: version
    value: "v1"
    type: text
  - name: doi-toolchain-id
    value: ${DOI_TOOLCHAIN_ID}
    type: text
  - name: slack-notifications
    value: "0"
    type: text
  - name: cos-endpoint
    value: ${COS_ENDPOINT}
    type: text
  - name: cos-bucket-name
    value: ${COS_BUCKET_NAME}
    type: text
private_worker: ${PRIVATE_WORKER}
