version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
#    - tekton-catalog-repo
    - tekton-definition-repo
    # - evidence-locker-repo
    # - incident-issues-repo
    - application-repo
    - servicenow
 
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'tekton-cd-compliance-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:

  tekton-definition-repo:
    service_id: github_integrated
    parameters:
      # repo_url: $env.repository
      repo_url: 'https://github.ibm.com/cocoa/tekton-compliance-catalog'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true
      
  application-repo:   
    service_id: github_integrated
    parameters:
      type: link
      has_issues: false
      enable_traceability: true
      legal: true
#   tekton-catalog-repo:
#     service_id: github_integrated
#     parameters:
#       repo_url: 'https://github.ibm.com/cocoa/tekton-compliance-catalog'
#       type: link
#       has_issues: false
#       enable_traceability: false
#       legal: true 

  incident-issues-repo:
    service_id: github_integrated
    parameters:
      type: link
      has_issues: false
      enable_traceability: false
      legal: true

  evidence-locker-repo:
    service_id: github_integrated
    parameters:
      type: link
      has_issues: false
      enable_traceability: false
      legal: true      

  build:
    service_id: pipeline
    parameters:
      services:
        - tekton-definition-repo
        # - tekton-catalog-repo
        - incident-issues-repo
        - evidence-locker-repo
        - customtool_servicenow
      name: 'tekton-pipeline-{{timestamp}}'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          IMAGE_NAME: '{{form.pipeline.parameters.app-name}}'
          # repo for Tekton definitions
          TEKTON_DEFINITION_REPO: tekton-definition-repo
          # TEKTON_CATALOG_REPO: tekton-catalog-repo
          # repo of your application to be build/deployed
          BRANCH: master
          # IBM Cloud cluster data
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          REPOSITORY: '{{form.application-repo.parameters.repo_url}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          # ServiceNow API token to create Change Requests
          SERVICENOW_TOKEN: '{{form.servicenow.parameters.api-token}}'
          SERVICENOW_URL: '{{form.customtool_servicenow.parameters.api-url}}'
          # GitHub Enterprise credentials to access the v3 REST API
          GHE_TOKEN: '{{form.pipeline.parameters.ghe-token}}'
          GHE_USER: '{{services.evidence-locker-repo.parameters.owner_id}}'
          # Issues repo to raise compliance related issues from the CI/CD
          INCIDENT_ISSUES_REPO: '{{form.incident-issues-repo.parameters.repo_url}}'
          EVIDENCE_LOCKER_REPO: '{{form.evidence-locker-repo.parameters.repo_url}}'
          # GH Label used on issues and PRs to indicate an emergency change
          EMERGENCY_LABEL: '{{form.pipeline.parameters.emergency-label}}'
        execute: true

  servicenow:
    service_id: customtool
    parameters:
      type: servicenow
      lifecyclePhase: "MANAGE"
      imageUrl:
        $ref: servicenow.svg
        $refType: image-data-uri
      documentationUrl: https://watson.service-now.com/ess_portal?id=kb_category&kb_category=92518934db4e3300fc0e389f9d961990
      name: ServiceNow Change Management
      dashboard_url: https://watson.service-now.com/ess_portal?id=ss_homepage
      description: IBM Cloud Employee Service Portal
      
form:
  
  pipeline:
    parameters:
      app-name: '{{services.application-repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
      build-cluster-namespace: staging
      emergency-label: EMERGENCY
      ghe-token: 
    schema:
      $ref: deploy.json
  
  customtool_servicenow: 
    parameters:
      api-url: https://watsontest.service-now.com/api/ibmwc/change
      api-token:
    schema:
      $ref: servicenow.json
