---
version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - tekton-definition-repo
    - tekton-catalog-repo
    - app-repo
    - incident-issues-repo
    - evidence-locker-repo
    - inventory-repo
    - servicenow
    - artifactoryComp
    - privateWorker
    - doi-toolchain
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'tekton-cd-compliance-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  privateWorker:
    service_id: private_worker
    parameters:
      name: private-worker

  artifactoryComp:
    service_id: artifactory
    parameters:
      name: 'registry-for-images'
      dashboard_url: 'https://na.artifactory.swg-devops.com'
      repository_url: 'https://wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com'
      repository_name: 'wcp-compliance-automation-team-docker-local'
      type: docker

  tekton-definition-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.tekton-definition-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true
      kind: ['pipeline']

  tekton-catalog-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.tekton-catalog-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true
      kind: ['pipeline']

  app-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.app-repo}}'
      type: link
      has_issues: false
      enable_traceability: true
      legal: true

  incident-issues-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.incident-issues-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true

  evidence-locker-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.evidence-locker-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true

  inventory-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.inventory-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true

  build:
    service_id: pipeline
    parameters:
      services:
        - tekton-definition-repo
        - tekton-catalog-repo
        - incident-issues-repo
        - evidence-locker-repo
        - inventory-repo
        - customtool_servicenow
        - customtool_doi-toolchain
      name: 'cd-pipeline'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          APP_NAME: '{{form.pipeline.parameters.app-name}}'
          # repo for Tekton definitions and catalog
          TEKTON_DEFINITION_REPO: tekton-definition-repo
          TEKTON_CATALOG_REPO: tekton-catalog-repo
          # repo of your application to be build/deployed
          REPOSITORY: '{{form.app-repo.parameters.repo_url}}'
          BRANCH: master
          # IBM Cloud cluster data
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          # ServiceNow API token to create Change Requests
          SERVICENOW_TOKEN: '{{form.customtool_servicenow.parameters.api-token}}'
          SERVICENOW_BASE_URL: '{{form.customtool_servicenow.parameters.api-url}}'
          SERVICENOW_CONFIGURATION_ITEM: '{{form.customtool_servicenow.parameters.configuration-item}}'
          CHANGEREQUEST_ID: '{{form.customtool_servicenow.parameters.changerequest-id}}'
          # Issues repo to raise compliance related issues from the CI/CD
          INCIDENT_ISSUES_REPO: '{{form.incident-issues-repo.parameters.repo_url}}'
          EVIDENCE_LOCKER_REPO: '{{form.evidence-locker-repo.parameters.repo_url}}'
          INVENTORY_REPO: inventory-repo
          INVENTORY_REPO_URL: '{{form.inventory-repo.parameters.repo_url}}'
          # GH Label used on issues and PRs to indicate an emergency change
          EMERGENCY_LABEL: '{{form.pipeline.parameters.emergency-label}}'
          ARTIFACTORY_DOCKER_CONFIG_JSON: '{{form.artifactoryComp.parameters.docker_config_json}}'
          # Private Worker for the pipeline
          PRIVATE_WORKER: '{{services.privateWorker.parameters.name}}'
          DOI_TOOLCHAIN_ID: '{{form.customtool_doi-toolchain.parameters.doi-toolchain-id}}'
        execute: true

  servicenow:
    service_id: customtool
    parameters:
      type: servicenow
      lifecyclePhase: "MANAGE"
      imageUrl:
        $ref: servicenow.svg
        $refType: image-data-uri
      documentationUrl: https://watson.service-now.com/ess_portal?id=kb_category&kb_category=92518934db4e3300fc0e389f9d961990
      name: ServiceNow Change Management
      dashboard_url: '{{form.customtool_servicenow.parameters.api-url}}'
      description: IBM Cloud Employee Service Portal

  doi-toolchain:
    service_id: customtool
    parameters:
      type: doi-toolchain
      lifecyclePhase: "LEARN"
      imageUrl:
        $ref: devops-insights.png
        $refType: image-data-uri
      documentationUrl: 'https://cloud.ibm.com/devops/insights/overviewNew?toolchainId={{form.customtool_doi-toolchain.parameters.doi-toolchain-id}}'
      name: Link DOI Toolchain
      dashboard_url: 'https://cloud.ibm.com/devops/insights/overviewNew?toolchainId={{form.customtool_doi-toolchain.parameters.doi-toolchain-id}}'
      description: The toolchain that contains the Devops Insights instance CD interacts with.

form:

  github_integrated:
    parameters:
      tekton-catalog-repo: 'https://github.ibm.com/one-pipeline/common-tekton-tasks'
      tekton-definition-repo: 'https://github.ibm.com/one-pipeline/compliance-cd-toolchain'
      app-repo:
      incident-issues-repo:
      evidence-locker-repo:
      inventory-repo:
    schema:
      $ref: repos.json

  pipeline:
    parameters:
      app-name: hello-compliance-app
      prod-cluster-namespace: default
      build-cluster-namespace: staging
      emergency-label: EMERGENCY
    schema:
      $ref: deploy.json

  customtool_servicenow:
    parameters:
      api-url: https://watsontest.service-now.com
      changerequest-id: notAvailable
      api-token:
      configuration-item:
    schema:
      $ref: servicenow.json

  customtool_doi-toolchain:
    parameters:
      doi-toolchain-id:
    schema:
      $ref: doi-toolchain.json
