---
version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - tekton-definition-repo
    - tekton-catalog-repo
    - incident-issues-repo
    - evidence-locker-repo
    - inventory-repo
    - servicenow
    - artifactoryComp
    - privateWorker
    - doi-toolchain
    - fortress
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'compliance-cd-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  kp-vault:
    service_id: keyprotect
    parameters:
      name: 'kp-compliance-secrets'

  hc-vault:
    service_id: hashicorpvault
    parameters:
      name: 'hc-compliance-secrets'
      server_url: 'https://vserv-test.sos.ibm.com:8200'
      dashboard_url: 'https://vserv-test.sos.ibm.com:8200/ui'
      authentication_method: 'approle'

  cos-bucket:
    service_id: customtool
    parameters:
      type: cos-bucket
      lifecyclePhase: "MANAGE"
      imageUrl:
        $ref: cos-logo.png
        $refType: image-data-uri
      documentationUrl: 'https://cloud.ibm.com/catalog/services/cloud-object-storage'
      name: Cloud Object Storage
      dashboard_url: 'https://cloud.ibm.com/catalog/services/cloud-object-storage'
      description: The information required to connect the toolchain with your Cloud Object Storage instance.

  slack:
    service_id: slack
    parametes:
      channel_name: ''
      api_token: ''
      team_url: ''

  privateWorker:
    service_id: private_worker
    parameters:
      name: private-worker

  artifactoryComp:
    service_id: artifactory
    parameters:
      name: 'registry-for-images'
      dashboard_url: 'https://na.artifactory.swg-devops.com'
      repository_url: 'https://wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com'
      repository_name: 'wcp-compliance-automation-team-docker-local'
      type: docker

  tekton-definition-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.tekton-definition-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true
      kind: ['pipeline']

  tekton-catalog-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.tekton-catalog-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true
      kind: ['pipeline']

  incident-issues-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.incident-issues-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true

  evidence-locker-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.evidence-locker-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true

  inventory-repo:
    service_id: github_integrated
    parameters:
      repo_url: '{{form.github_integrated.parameters.inventory-repo}}'
      type: link
      has_issues: false
      enable_traceability: false
      legal: true

  build:
    service_id: pipeline
    parameters:
      services:
        - tekton-definition-repo
        - tekton-catalog-repo
        - incident-issues-repo
        - evidence-locker-repo
        - inventory-repo
        - customtool_servicenow
        - customtool_doi-toolchain
      name: 'cd-pipeline'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          APP_NAME: '{{form.pipeline.parameters.app-name}}'
          # repo for Tekton definitions and catalog
          TEKTON_DEFINITION_REPO: tekton-definition-repo
          TEKTON_CATALOG_REPO: tekton-catalog-repo
          # repo of your application to be build/deployed
          BRANCH: master
          # IBM Cloud cluster data
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          # ServiceNow API token to create Change Requests
          SERVICENOW_TOKEN: '{{form.customtool_servicenow.parameters.api-token}}'
          SERVICENOW_BASE_URL: '{{form.customtool_servicenow.parameters.api-url}}'
          SERVICENOW_CONFIGURATION_ITEM: '{{form.customtool_servicenow.parameters.configuration-item}}'
          INVENTORY_REPO: inventory-repo
          # GH Label used on issues and PRs to indicate an emergency change
          EMERGENCY_LABEL: '{{form.pipeline.parameters.emergency-label}}'
          SOURCE_ENVIRONMENT: '{{form.pipeline.parameters.source-environment}}'
          TARGET_ENVIRONMENT: '{{form.pipeline.parameters.target-environment}}'
          ARTIFACTORY_DOCKER_CONFIG_JSON: '{{form.artifactoryComp.parameters.docker_config_json}}'
          # Private Worker for the pipeline
          PRIVATE_WORKER: '{{services.privateWorker.parameters.name}}'
          DOI_TOOLCHAIN_ID: '{{form.customtool_doi-toolchain.parameters.doi-toolchain-id}}'
          COS_BUCKET_NAME: '{{form.customtool_cos-bucket.parameters.cos-bucket-name}}'
          COS_ENDPOINT: '{{form.customtool_cos-bucket.parameters.cos-endpoint}}'
        execute: true

  servicenow:
    service_id: customtool
    parameters:
      type: servicenow
      lifecyclePhase: "MANAGE"
      imageUrl:
        $ref: servicenow.svg
        $refType: image-data-uri
      documentationUrl: https://watson.service-now.com/ess_portal?id=kb_category&kb_category=92518934db4e3300fc0e389f9d961990
      name: ServiceNow Change Management
      dashboard_url: '{{form.customtool_servicenow.parameters.api-url}}'
      description: IBM Cloud Employee Service Portal

  doi-toolchain:
    service_id: customtool
    parameters:
      type: doi-toolchain
      lifecyclePhase: "LEARN"
      imageUrl:
        $ref: devops-insights.png
        $refType: image-data-uri
      documentationUrl: 'https://cloud.ibm.com/devops/insights/overviewNew?toolchainId={{form.customtool_doi-toolchain.parameters.doi-toolchain-id}}'
      name: Link DOI Toolchain
      dashboard_url: 'https://cloud.ibm.com/devops/insights/overviewNew?toolchainId={{form.customtool_doi-toolchain.parameters.doi-toolchain-id}}'
      description: The toolchain that contains the Devops Insights instance CD interacts with.

  fortress:
    service_id: security_compliance
    parameters:
      evidence_repo_name:
      name:

form:

  github_integrated:
    parameters:
      tekton-catalog-repo: 'https://github.ibm.com/one-pipeline/common-tekton-tasks'
      tekton-definition-repo: 'https://github.ibm.com/one-pipeline/compliance-cd-toolchain'
      incident-issues-repo:
      evidence-locker-repo:
      inventory-repo:
    schema:
      $ref: repos.json

  pipeline:
    parameters:
      app-name: hello-compliance-app
      prod-cluster-namespace: default
      build-cluster-namespace: staging
      emergency-label: EMERGENCY
      source-environment: master
      target-environment: prod
    schema:
      $ref: deploy.json

  customtool_servicenow:
    parameters:
      api-url: https://watsontest.service-now.com
      api-token:
      configuration-item:
    schema:
      $ref: servicenow.json

  customtool_doi-toolchain:
    parameters:
      doi-toolchain-id:
    schema:
      $ref: doi-toolchain.json

  customtool_cos-bucket:
    parameters:
      cos-bucket-name: ''
      cos-endpoint: ''
    schema:
      $ref: cos.json
