---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cd-binding
spec:
  params:
    - name: event-payload
      value: $(event)
    - name: target-environment-ref
      value: $(event.ref)
