---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: cd-binding
spec:
  params:
    - name: repository
    # value: "https://github.com/open-toolchain/hello-tekton"
    - name: revision
    # value: "master"
