---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-mode-cd-pipeline
spec:
  params:
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: compliance-baseimage
      description: base image to run most of the built-in pipeline code

  workspaces:
    - name: artifacts

  tasks:
    - name: prod-start
      taskRef:
        name: cd-start
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: setup

    - name: prod-setup
      taskRef:
        name: run-stage
      runAfter:
        - prod-start
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: setup
        - name: image
          value: $(tasks.prod-start.results.image)
        - name: script
          value: $(tasks.prod-start.results.script)
        - name: configmap
          value: $(tasks.prod-start.results.configmap)
        - name: secret
          value: $(tasks.prod-start.results.secret)
        - name: abort-on-failure
          value: $(tasks.prod-start.results.abort-on-failure)
        - name: dind
          value: $(tasks.prod-start.results.dind)
        - name: image-pull-policy
          value: $(tasks.prod-start.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: deploy

    - name: prod-deployment
      taskRef:
        name: run-stage
      runAfter:
        - prod-setup
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: deploy
        - name: image
          value: $(tasks.prod-setup.results.image)
        - name: script
          value: $(tasks.prod-setup.results.script)
        - name: configmap
          value: $(tasks.prod-setup.results.configmap)
        - name: secret
          value: $(tasks.prod-setup.results.secret)
        - name: abort-on-failure
          value: $(tasks.prod-setup.results.abort-on-failure)
        - name: dind
          value: $(tasks.prod-setup.results.dind)
        - name: image-pull-policy
          value: $(tasks.prod-setup.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: acceptance-test

    - name: prod-acceptance-tests
      runAfter:
        - prod-deployment
      taskRef:
        name: run-stage
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: acceptance-test
        - name: image
          value: $(tasks.prod-deployment.results.image)
        - name: script
          value: $(tasks.prod-deployment.results.script)
        - name: configmap
          value: $(tasks.prod-deployment.results.configmap)
        - name: secret
          value: $(tasks.prod-deployment.results.secret)
        - name: abort-on-failure
          value: $(tasks.prod-deployment.results.abort-on-failure)
        - name: dind
          value: $(tasks.prod-deployment.results.dind)
        - name: image-pull-policy
          value: $(tasks.prod-deployment.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
