apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: registryNamespace
      description: the ibmcloud registry namespace
    - name: registryRegion
      description: the ibmcloud registry region
      default: us-south
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
    - name: clusterRegion
      description: The IBM Cloud Kubernetes cluster region
      default: us-south
    - name: clusterNamespace
      description: The Kubernetes cluster namespace
      default: prod
    - name: gheToken
      description: the GHE token
    - name: gheUser
      description: the GHE user
    - name: gheIssueRepo
      description: Incident issues repo url
    - name: evidenceLockerRepo
      description: Evidence locker repo url
    - name: ghEmergencyLabel
      description: the name of the emergency label
    - name: app
      description: name of the deployed app or service
    - name: serviceNowToken
      description: API token for ServiceNow to handle Change Requests
    - name: changeRequestNumber
      description: ServiceNow CR number
      default: "notAvailable"
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-context
      data:
        CR_NAMESPACE: $(params.registryNamespace)
        CR_REGION: $(params.registryRegion)
        CLUSTER_NAME: $(params.cluster)
        CLUSTER_REGION: $(params.clusterRegion)
        CLUSTER_NAMESPACE: $(params.clusterNamespace)
        EMERGENCY_LABEL: $(params.ghEmergencyLabel)
        APPLICATION: $(params.app)
        INCIDENT_ISSUE_REPO: $(params.gheIssueRepo)
        EVIDENCE_LOCKER_REPO: $(params.evidenceLockerRepo)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secrets
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
        GHE_USER: $(params.gheUser)
        GHE_TOKEN: $(params.gheToken)
        SERVICENOW_TOKEN: $(params.serviceNowToken)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: cd-pipeline
        params:
          - name: repository
            value: $(params.repository)          
          - name: revision
            value: $(params.revision)
          - name: image
            value: $(params.image)
          - name: changeRequestNumber
            value: $(params.changeRequestNumber)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      # value: "https://github.com/open-toolchain/hello-tekton"
    - name: revision
      # value: "master"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: cd-template