---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the git repo
      default: master
    - name: ibmcloud-api-key
      description: IBM Cloud API key with access to the toolchain
    - name: servicenow-api-token
      description: A valid ServiceNow API token
    - name: servicenow-api-url
      description: The ServiceNow API URL you wish to use (test or live)
    - name: servicenow-configuration-item
      description: The name of the service to be deployed as it is registered in ServiceNow
    - name: cluster
      description: iks cluster name
    - name: cluster-region
      description: iks cluster region
    - name: cluster-namespace
      description: iks cluster namespace
    - name: application
      description: application name
    - name: emergency-label
      description: emergency label for change request generation
    - name: evidence-locker-url
      description: evidence locker repo
    - name: change-request-id
      description: optional ServiceNow Change Request ID
      default: "notAvailable"
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: version
      description: App version

  workspaces:
    - name: artifacts

  tasks:
    - name: get-git-credentials
      taskRef:
        name: git-get-credentials
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: repository
          value: $(params.repository)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-clone-evidence-repo
      taskRef:
        name: git-clone
      runAfter:
        - get-git-credentials
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: repository
          value: $(params.evidence-locker-url)
        - name: branch
          value: "master"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-clone-repo
      taskRef:
        name: git-clone
      runAfter:
        - pipeline-clone-evidence-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-clone-inventory-repo
      taskRef:
        name: git-clone-inventory-repo
      runAfter:
        - pipeline-clone-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: version
          value: $(params.version)

    - name: pipeline-get-evidence-locker-path
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          value: .services[] | select(.toolchain_binding.name=="evidence-locker-repo") | .parameters.repo_name
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-get-toolchain-crn
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          value: .crn
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-get-evidence-path
      taskRef:
        name: inventory-get-pipeline-run-id
      runAfter:
        - pipeline-clone-inventory-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: app-name
          value: $(params.application)
        - name: version
          value: $(params.version)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-evidence-summarize
      taskRef:
        name: evidence-summarize
      workspaces:
        - name: evidence-locker
          workspace: artifacts
      params:
        - name: evidence-repo-path
          value: $(tasks.pipeline-get-evidence-locker-path.results.extracted-value)
        - name: path-list
          value: ci/$(tasks.pipeline-get-evidence-path.results.pipeline-run-id)
        - name: toolchain-crn
          value: $(tasks.pipeline-get-toolchain-crn.results.extracted-value)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-create-cr
      taskRef:
        name: servicenow-create-change-request
      runAfter:
        - pipeline-evidence-summarize
        - get-git-credentials
        - pipeline-clone-inventory-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: repository
          value: $(params.repository)
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(params.servicenow-api-url)
        - name: servicenow-configuration-item
          value: $(params.servicenow-configuration-item)
        - name: cluster
          value: $(params.cluster)
        - name: cluster-region
          value: $(params.cluster-region)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
        - name: application
          value: $(params.application)
        - name: emergency-label
          value: $(params.emergency-label)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: change-request-id
          value: $(params.change-request-id)
        - name: collect-evidence
          value: "true"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-inventory-cr-add
      taskRef:
        name: inventory-cr-add
      runAfter:
        - pipeline-create-cr
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: version
          value: $(params.version)

    - name: pipeline-check-cr-approval
      taskRef:
        name: servicenow-check-change-request-approval
      runAfter:
        - pipeline-inventory-cr-add
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(params.servicenow-api-url)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: collect-evidence
          value: "true"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-deployment
      taskRef:
        name: iks-deploy
      runAfter:
        - pipeline-clone-repo
        - pipeline-check-cr-approval
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: cluster-name
          value: $(params.cluster)
        - name: cluster-region
          value: $(params.cluster-region)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
        - name: allow-create-route
          value: "false"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-merge-cr-inventory-branch
      taskRef:
        name: inventory-apply
      runAfter:
        - pipeline-deployment
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: pipeline-close-cr
      taskRef:
        name: servicenow-close-change-request
      runAfter:
        - pipeline-merge-cr-inventory-branch
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(params.servicenow-api-url)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: collect-evidence
          value: "true"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
