---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: pipeline-pvc
      description: pipeline pvc name place holder
    - name: repository
      description: the git repo
    - name: revision
      description: the git repo
      default: master
    - name: ibmcloud-api-key
      description:
    - name: servicenow-api-token
      description:
    - name: servicenow-api-url
      description:
    - name: servicenow-configuration-item
      description:
    - name: cluster
      description:
    - name: cluster-region
      description:
    - name: cluster-namespace
      description:
    - name: application
      description:
    - name: emergency-label
      description:
    - name: evidence-locker-url
      description:
    - name: pipeline-run-id
      description:
    - name: image
      description: the docker image to be deployed
      default: "noImage"
    - name: change-request-id
      description: optional ServiceNow Change Request ID
      default: "notAvailable"
  tasks:

    - name: get-git-credentials
      taskRef:
        name: get-git-credentials
      params:
        - name: credentials-pvc
          value: $(params.pipeline-pvc)
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: repository
          value: $(params.repository)

    - name: pipeline-clone-repo
      taskRef:
        name: git-clone
      runAfter:
        - get-git-credentials
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.revision)

    - name: check-github-statuses
      runAfter:
        - pipeline-clone-repo
      taskRef:
        name: check-github-statuses-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: pipelineRunId
          value: $(params.pipeline-run-id)
        - name: target-branch
          value: $(params.revision)
