---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: pipeline-pvc
      description: pipeline pvc name place holder
    - name: repository
      description: the git repo
    - name: revision
      description: the git repo
      default: master
    - name: ibmcloud-api-key
      description:
    - name: servicenow-api-token
      description:
    - name: servicenow-api-url
      description:
    - name: servicenow-configuration-item
      description:
    - name: cluster
      description:
    - name: cluster-region
      description:
    - name: cluster-namespace
      description:
    - name: application
      description:
    - name: emergency-label
      description:
    - name: evidence-locker-url
      description:
    - name: pipeline-run-id
      description:
    - name: change-request-id
      description: optional ServiceNow Change Request ID
      default: "notAvailable"
  tasks:

    - name: get-git-credentials
      taskRef:
        name: get-git-credentials
      params:
        - name: credentials-pvc
          value: $(params.pipeline-pvc)
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: repository
          value: $(params.repository)

    - name: pipeline-clone-repo
      taskRef:
        name: git-clone
      runAfter:
        - get-git-credentials
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.revision)

    - name: pipeline-clone-inventory-repo
      taskRef:
        name: clone-inventory-repo
      runAfter:
        - pipeline-clone-repo
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)

    - name: pipeline-create-cr
      taskRef:
        name: create-change-request
      runAfter:
        - get-git-credentials
        - pipeline-clone-inventory-repo
      params:
        - name: pipeline-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(params.servicenow-api-url)
        - name: servicenow-configuration-item
          value: $(params.servicenow-configuration-item)
        - name: cluster
          value: $(params.cluster)
        - name: cluster-region
          value: $(params.cluster-region)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
        - name: application
          value: $(params.application)
        - name: emergency-label
          value: $(params.emergency-label)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: pipeline-run-id
          value: $(params.pipeline-run-id)
        - name: change-request-id
          value: $(params.change-request-id)
        - name: collect-evidence
          value: "1"

    - name: pipeline-check-cr-approval
      taskRef:
        name: check-change-request-approval
      runAfter:
        - pipeline-create-cr
      params:
        - name: pipeline-pvc
          value: $(params.pipeline-pvc)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: pipeline-run-id
          value: $(params.pipeline-run-id)
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(params.servicenow-api-url)

    - name: pipeline-deployment
      taskRef:
        name: run-deployment-task
      runAfter:
        - pipeline-clone-repo
        - pipeline-check-cr-approval
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: cluster
          value: $(params.cluster)
        - name: cluster-region
          value: $(params.cluster-region)
        - name: cluster-namespace
          value: $(params.cluster-namespace)

    - name: pipeline-close-cr
      taskRef:
        name: close-change-request
      runAfter:
        - pipeline-deployment
      params:
        - name: pipeline-pvc
          value: $(params.pipeline-pvc)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: pipeline-run-id
          value: $(params.pipeline-run-id)
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(params.servicenow-api-url)
