---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the git repo
      default: master
    - name: ibmcloud-api-key
      description: IBM Cloud API key with access to the toolchain
    - name: servicenow-api-token
      description: A valid ServiceNow API token
    - name: servicenow-api-base-url
      description: The ServiceNow API Base URL you wish to use (test or live)
    - name: servicenow-configuration-item
      description: The name of the service to be deployed as it is registered in ServiceNow
    - name: cluster
      description: iks cluster name
    - name: cluster-region
      description: iks cluster region
    - name: cluster-namespace
      description: iks cluster namespace
    - name: application
      description: application name
    - name: emergency-label
      description: emergency label for change request generation
    - name: evidence-locker-url
      description: evidence locker repo
    - name: change-request-id
      description: optional ServiceNow Change Request ID
      default: "notAvailable"
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: version
      description: App version

  workspaces:
    - name: artifacts

  tasks:
    - name: prod-get-git-credentials
      taskRef:
        name: git-get-credentials
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: repository
          value: $(params.repository)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-clone-evidence-repo
      taskRef:
        name: git-clone
      runAfter:
        - prod-get-git-credentials
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: repository
          value: $(params.evidence-locker-url)
        - name: branch
          value: "master"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-clone-repo
      taskRef:
        name: git-clone
      runAfter:
        - prod-clone-evidence-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-get-deployment-app
      taskRef:
        name: get-deployment-app
      runAfter:
        - prod-clone-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: app-directory
          value: "$(tasks.prod-clone-repo.results.directory-name)"
        - name: deployment-file
          value: "deployment.yml"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-clone-inventory-repo
      taskRef:
        name: git-clone-inventory-repo
      runAfter:
        - prod-clone-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: version
          value: $(params.version)
        - name: app-name
          value: $(params.application)

    - name: prod-get-evidence-locker-path
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          value: .services[] | select(.toolchain_binding.name=="evidence-locker-repo") | .parameters.repo_name
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-get-toolchain-crn
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          value: .crn
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-get-evidence-path
      taskRef:
        name: inventory-get-pipeline-run-id
      runAfter:
        - prod-clone-inventory-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: app-name
          value: $(params.application)
        - name: version
          value: $(params.version)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-summarize-evidence
      taskRef:
        name: evidence-summarize
      workspaces:
        - name: evidence-locker
          workspace: artifacts
      params:
        - name: evidence-repo-path
          value: $(tasks.prod-get-evidence-locker-path.results.extracted-value)
        - name: path-list
          value: ci/$(tasks.prod-get-evidence-path.results.pipeline-run-id)
        - name: toolchain-crn
          value: $(tasks.prod-get-toolchain-crn.results.extracted-value)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-format-evidence-summary
      runAfter:
        - prod-summarize-evidence
      taskRef:
        name: evidence-format-summary
      workspaces:
        - name: evidence-locker
          workspace: artifacts
      params:
        - name: evidence-repo-path
          value: $(tasks.prod-get-evidence-locker-path.results.extracted-value)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: summary-path
          value: $(tasks.prod-summarize-evidence.results.summary-path)

    - name: prod-create-change-request-urls
      params:
        - name: servicenow-api-base-url
          value: $(params.servicenow-api-base-url)
      taskSpec:
        params:
          - name: servicenow-api-base-url
        results:
          - name: change-request-url
          - name: servicenow-api-url
        steps:
          - name: create-change-request-urls
            image: ibmcom/pipeline-base-image:2.6
            env:
              - name: CHANGE_API_PATH
                value: "api/ibmwc/change"
              - name: CHANGE_REQUEST_URL_PATH
                value: "nav_to.do?uri=change_request.do?sys_id="
              - name: SERVICENOW_BASE_URL
                value: $(params.servicenow-api-base-url)
            script: |
              echo -n "${SERVICENOW_BASE_URL}/${CHANGE_REQUEST_URL_PATH}" > $(results.change-request-url.path)
              echo -n "${SERVICENOW_BASE_URL}/${CHANGE_API_PATH}" > $(results.servicenow-api-url.path)

    - name: prod-create-cr
      taskRef:
        name: servicenow-create-change-request
      runAfter:
        - prod-summarize-evidence
        - prod-get-git-credentials
        - prod-clone-inventory-repo
        - prod-create-change-request-urls
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: application
          value: "$(tasks.prod-get-deployment-app.results.app-name)"
        - name: repository
          value: $(params.repository)
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(tasks.prod-create-change-request-urls.results.servicenow-api-url)
        - name: servicenow-configuration-item
          value: $(params.servicenow-configuration-item)
        - name: cluster
          value: $(params.cluster)
        - name: cluster-region
          value: $(params.cluster-region)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
        - name: emergency-label
          value: $(params.emergency-label)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: change-request-id
          value: $(params.change-request-id)
        - name: change-request-url
          value: $(tasks.prod-create-change-request-urls.results.change-request-url)
        - name: collect-evidence
          value: "true"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-add-cr-inventory
      taskRef:
        name: inventory-cr-add
      runAfter:
        - prod-create-cr
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: repository
          value: $(params.application)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: version
          value: $(params.version)

    - name: prod-check-cr-approval
      taskRef:
        name: servicenow-check-change-request-approval
      runAfter:
        - prod-add-cr-inventory
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(tasks.prod-create-change-request-urls.results.servicenow-api-url)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: collect-evidence
          value: "true"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-create-namespace
      taskRef:
        name: iks-create-namespace
      runAfter:
        - prod-check-cr-approval
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: cluster-name
          value: $(params.cluster)
        - name: cluster-region
          value: $(params.cluster-region)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-create-image-pull-secrets
      taskRef:
        name: iks-create-pull-secrets
      runAfter:
        - prod-create-namespace
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: cluster-name
          value: $(params.cluster)
        - name: cluster-region
          value: $(params.cluster-region)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
        - name: registry-url
          value: $(tasks.prod-clone-inventory-repo.results.registry-url)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-deployment
      taskRef:
        name: iks-deploy
      runAfter:
        - prod-clone-repo
        - prod-create-image-pull-secrets
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api-key
          value: $(params.ibmcloud-api-key)
        - name: cluster-name
          value: $(params.cluster)
        - name: cluster-region
          value: $(params.cluster-region)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
        - name: allow-create-route
          value: "false"
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-merge-cr-inventory-branch
      taskRef:
        name: inventory-apply
      runAfter:
        - prod-deployment
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: prod-close-cr
      taskRef:
        name: servicenow-close-change-request
      runAfter:
        - prod-merge-cr-inventory-branch
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: servicenow-api-token
          value: $(params.servicenow-api-token)
        - name: servicenow-api-url
          value: $(tasks.prod-create-change-request-urls.results.servicenow-api-url)
        - name: evidence-locker-url
          value: $(params.evidence-locker-url)
        - name: collect-evidence
          value: "true"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
