apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
      default: master
    - name: image
      description: the image to be deployed
    - name: changeRequestNumber
      description: ServiceNow CR number
      default: "notAvailable"
  tasks:
    - name: pipeline-deploy-task
      taskRef:
        name: deploy-task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: image
          value: $(params.image)
        - name: changeRequestNumber
          value: $(params.changeRequestNumber)