---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: promotion-template
spec:
  params:
    - name: application
      description: name of the deployed app or service
    - name: source-environment
      description: promotion source, this can be overridden (defaults to master)
      default: "master"
    - name: target-environment
      description: promotion target, this can be overridden (defaults to prod)
      default: "prod"
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: slack-notifications
      description: toggles slack notifications

    # 'create-promotion-pull-request' parameters for the service now change request ticket
    - name: priority
      description: priority of the service now change request
      default: "Critical | High | Moderate | Low | Planning"
    - name: assignee
      description: functional id or an email who will be assigned to the change request in service now
      default: "_PROVIDE INFORMATION_"
    - name: description
      description: additional description in the change request
      default: "_PROVIDE INFORMATION_"
    - name: purpose
      description: the reason of why the change request is needed
      default: "_PROVIDE INFORMATION_"
    - name: impact
      description: explanation what the changes will impact
      default: "_PROVIDE INFORMATION_"
    - name: backout-plan
      description: details how the change will be rolled back in case of a failure
      default: "Revert to the previous release."
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
      metadata:
        name: sa-pullsecret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: promotion-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: application
            value: $(params.application)
          - name: source-environment
            value: $(params.source-environment)
          - name: target-environment
            value: $(params.target-environment)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: slack-notifications
            value: $(params.slack-notifications)

          - name: priority
            value: $(params.priority)
          - name: assignee
            value: $(params.assignee)
          - name: description
            value: $(params.description)
          - name: purpose
            value: $(params.purpose)
          - name: impact
            value: $(params.impact)
          - name: backout-plan
            value: $(params.backout-plan)
        serviceAccountName: sa-pullsecret
