---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: promotion-pipeline
spec:
  params:
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: compliance-baseimage
      description: base image to run most of the built-in pipeline code
  workspaces:
    - name: artifacts

  tasks:
    - name: inventory-promotion
      taskRef:
        name: inventory-promotion
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
