---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: promotion-template
spec:
  params:
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: priority
      description: priority of the service now change request
    - name: assignee
      description: functional id or an email who will be assigned to the change request in service now
    - name: event-payload
      description: event payload from the trigger webhook
      default: ""
    - name: compliance-baseimage
      description: one-pipeline baseimage to run most of the built-in pipeline code
      default: !<false> "wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/compliance-baseimage:0.2.3@sha256:5e46451e43287457ef78922c244169aa60138d828e44db3f064c724c7849789a"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
      metadata:
        name: sa-pullsecret
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: trigger
        labels:
          app.kubernetes.io/version: "1.0.0"
      data:
        payload.json: |
          $(params.event-payload)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: promotion-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: compliance-baseimage
            value: $(params.compliance-baseimage)
          - name: priority
            value: $(params.priority)
          - name: assignee
            value: $(params.assignee)
        serviceAccountName: sa-pullsecret