---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: promotion-pipeline
spec:
  params:
    - name: application
      description: the name of the application that's going to be promoted (defaults to the application name)
    - name: source
      description: promotion source
    - name: target
      description: promotion target
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: slack-notifications
      description: toggles slack notifications

  workspaces:
    - name: artifacts

  tasks:
    - name: setup-variables
      params:
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: target
          value: $(params.target)
        - name: application
          value: $(params.application)
      taskSpec:
        params:
          - name: pipeline-debug
          - name: target
          - name: application
        results:
          - name: inventory-owner
          - name: inventory-name
          - name: pipeline-run-id
          - name: pull-request-title
        stepTemplate:
          env:
            - name: PIPELINE_DEBUG
              value: $(params.pipeline-debug)
            - name: PIPELINE_RUN_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
        steps:
          - name: setup
            image: ibmcom/pipeline-base-image:2.6
            script: |
              #!/bin/bash
              set -e -o pipefail
              if [ $PIPELINE_DEBUG == 1 ]; then
                pwd
                env
                trap env EXIT
                set -x
              fi
              echo -n "$PIPELINE_RUN_ID" | tee "$(results.pipeline-run-id.path)"
              if [ "$(params.application)" == "" ]; then
                echo -n "Promote applications from 'master' to '$(params.target)'" | tee "$(results.pull-request-title.path)"
              else
                echo -n "Promote '$(params.application)' from 'master' to '$(params.target)'" | tee "$(results.pull-request-title.path)"
              fi

    - name: get-inventory-url
      taskRef:
        name: toolchain-extract-value
      runAfter:
        - setup-variables
      params:
        - name: expression
          value: '.services[] | select(.toolchain_binding.name=="inventory-repo") | .parameters.owner_id + "/" + .parameters.repo_name'

    - name: get-inventory-variables
      runAfter:
        - get-inventory-url
      params:
        - name: inventory-url
          value: $(tasks.get-inventory-url.results.extracted-value)
      taskSpec:
        params:
          - name: inventory-url
        results:
          - name: inventory-owner
          - name: inventory-name
          - name: inventory-url
        steps:
          - name: get-owner-and-repo-name
            image: ibmcom/pipeline-base-image:2.6
            script: |
              #!/usr/bin/env python3
              url = "$(params.inventory-url)"
              splitted = url.split("/")
              with open("$(results.inventory-owner.path)", "w") as owner_out:
                owner_out.write(splitted[-2])
              with open("$(results.inventory-name.path)", "w") as name_out:
                name_out.write(splitted[-1])
              with open("$(results.inventory-url.path)", "w") as url_out:
                url_out.write("https://github.ibm.com/$(params.inventory-url)")

    - name: get-git-credentials
      taskRef:
        name: git-get-credentials
      runAfter:
        - get-inventory-url
      workspaces:
        - name: artifacts
          workspace: artifacts
        - name: secrets
          workspace: artifacts
      params:
        - name: repository
          value: $(tasks.get-inventory-variables.results.inventory-url)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: clone-inventory-repo
      taskRef:
        name: git-clone
      runAfter:
        - get-git-credentials
      workspaces:
        - name: artifacts
          workspace: artifacts
        - name: secrets
          workspace: artifacts
      params:
        - name: repository
          value: $(tasks.get-inventory-variables.results.inventory-url)
        - name: branch
          value: "master"
        - name: git-user
          value: $(tasks.get-git-credentials.results.git-auth-user)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: inventory-promote
      taskRef:
        name: inventory-promote
      runAfter:
        - clone-inventory-repo
      workspaces:
        - name: artifacts
          workspace: artifacts
        - name: secrets
          workspace: artifacts
      params:
        - name: app-name
          value: $(params.application)
        - name: source
          value: $(params.source)
        - name: target
          value: $(params.target)
        - name: branch
          value: $(tasks.setup-variables.results.pipeline-run-id)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: create-promotion-pull-request
      taskRef:
        name: github-create-pull-request
      runAfter:
        - inventory-promote
        - get-inventory-variables
      workspaces:
        - name: secrets
          workspace: artifacts
      params:
        - name: owner
          value: $(tasks.get-inventory-variables.results.inventory-owner)
        - name: repository
          value: $(tasks.get-inventory-variables.results.inventory-name)
        - name: head
          value: $(tasks.setup-variables.results.pipeline-run-id)
        - name: base
          value: $(params.target)
        - name: title
          value: $(tasks.setup-variables.results.pull-request-title)
        - name: body
          value: |
            This Pull Request was created by an automated build promotion. Pipeline Run ID: $(tasks.setup-variables.results.pipeline-run-id)

            # Priority
            <!-- Select the priority of this change -->
            <priority>

            Critical | High | Moderate | Low | Planning

            </priority>

            # Change Request assignee
            <!-- The functional ID or the person's email who will be assigned to the Change Request in ServiceNow -->
            <!-- Both of them need access to the ServiceNow -->
            <!-- Note: This is not the approver of the Change Request -->
            <assignedto>

              _PROVIDE INFORMATION_

            </assignedto>

            # Additional Description
            <!-- Some description of the change, implementation steps -->
            <!-- This field will be appended with the commit messages of the content of the PR, -->
            <!-- and any PR description that was included since the last PR into this branch -->
            <description>

              _PROVIDE INFORMATION_

            </description>

            # Purpose/Goal
            <!-- Write the reason of why the change is needed -->
            <purpose>

              _PROVIDE INFORMATION_

            </purpose>

            # Explanation of Impact
            <!-- Write down what this Change Implementation will impact -->
            <impact>

              _PROVIDE INFORMATION_

            </impact>

            # Backout Plan
            <!-- Write some details how the change will be rolled back in case of a failure -->
            <backoutplan>

              Revert to the previous release.

            </backoutplan>

    - name: notify-pipeline-end
      conditions:
        - conditionRef: is-equal
          params:
            - name: left
              value: $(params.slack-notifications)
            - name: right
              value: "1"
      taskRef:
        name: slack-post-message
      runAfter:
        - create-promotion-pull-request
      workspaces:
        - name: workspace
          workspace: artifacts
      params:
        - name: message-script
          value: |
              #!/usr/bin/env python3
              import os
              print("Promotion Pipeline finished!")
              print("<https://cloud.ibm.com/devops/pipelines/tekton/" + os.getenv("PIPELINE_ID") + "/runs/" + os.getenv("PIPELINE_RUN_ID") + "?env_id=ibm:yp:" + os.getenv("TOOLCHAIN_REGION") + "|See the Pipeline Logs>")
              print("<$(tasks.create-promotion-pull-request.results.pull-request-url)|See the Promotion Pull Request>")
