---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deployment-delta-reducer
spec:
  workspaces:
    - name: artifacts
      mountPath: /artifacts

  params:
    - name: deployment-delta-path
    - name: inventory-entries-list-path

  results:
    - name: application-name

  steps:
    - name: reduce
      image: ibmcom/pipeline-base-image:2.9
      workingDir: $(workspaces.artifacts.path)
      script: |
        #!/bin/bash

        #
        # THIS TASK IS TO MAKE SURE OUR SETUP WITH
        # A SINGLE INVENTORY ENTRY STILL KEEPS WORKING
        #
        # CAN BE REMOVED, WHEN WE ITERATE OVER
        # THE CHANGED INVENTORY ENTRIES
        # INSTEAD OF EXPECTING A SINGLE ENTRY
        #

        set -e -o pipefail

        deployment_delta_json="$(cat $(params.deployment-delta-path))"

        app=$(echo $deployment_delta_json | jq -r '.[0] // ""')

        if [ -z $app ]; then
          inventory_entries_json="$(cat $(params.inventory-entries-list-path))"
          app=$(echo $inventory_entries_json | jq -r '.[0] // ""')
        fi

        if [ -z $app ]; then
          echo "ERROR: no entries found in inventory, check your promotion targets"
          exit 1
        fi

        echo -n "${app}" | tee $(results.application-name.path)
