---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag-inventory
spec:
  workspaces:
    - name: secrets
      mountPath: /secrets
  params:
    - name: inventory-url
    - name: target-environment
    - name: pipeline-debug
      default: "0"
    - name: git-api-token-key
      default: "git-token"
  stepTemplate:
    env:
      - name: TARGET_ENV
        value: $(params.target-environment)
      - name: INVENTORY_URL
        value: $(params.inventory-url)
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
      - name: PIPELINE_RUN_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
  steps:
    - name: add-label
      image: wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/ibm-compliance-automation:1.1.8@sha256:de2d767a5295334959955b39a681cb78e103addd09c3d6c311fa53ad724fcaea
      script: |
        #!/bin/bash

        if [ $PIPELINE_DEBUG == 1 ]; then
          pwd
          env
          trap env EXIT
          set -x
        fi

        export GHE_TOKEN=$(cat "/secrets/$(params.git-api-token-key)")

        GHE_REPO=$(echo "$INVENTORY_URL" | cut -f5 -d/)
        GHE_ORG=$(echo "$INVENTORY_URL" | cut -f4 -d/)

        cocoa inventory label add \
          --org="${GHE_ORG}" \
          --repo="${GHE_REPO}" \
          --environment="${TARGET_ENV}" \
          "${PIPELINE_RUN_ID}"

        if [ $? -ne 0 ]; then
          echo "The target branch cannot be found, please run the promotion pipeline first!"
          exit 1
        fi
