---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inventory-promotion
spec:
  params:
    - name: compliance-baseimage
      description: base image to run most of the built-in pipeline code
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
    - name: priority
      description: priority of the service now change request
    - name: assignee
      description: functional id or an email who will be assigned to the change request in service now

  workspaces:
    - name: artifacts
      mountPath: /artifacts

  volumes:
    - name: config
      emptyDir: {}
    - name: environment-properties
      configMap:
        name: environment-properties
    - name: secure-properties
      secret:
        secretName: secure-properties
    - name: toolchain
      configMap:
        name: toolchain
    - name: trigger
      configMap:
        name: trigger

  stepTemplate:
    env:
      - name: ONE_PIPELINE_PATH
        value: "/opt/one-pipeline"
      - name: WORKSPACE
        value: "$(workspaces.artifacts.path)"
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
      - name: PIPELINE_RUN_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
      - name: PIPELINE_RUN_URL
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
  steps:
    - name: promote
      image: $(params.compliance-baseimage)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
        - name: trigger
          mountPath: /trigger
      script: |
        #!/bin/bash

        echo -n "$(params.priority)" >> /config/priority
        echo -n "$(params.assignee)" >> /config/assignee

        . "${ONE_PIPELINE_PATH}/internal/promotion"
