---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-deployment-app
spec:
  params:
    - name: deployment-file
    - name: app-directory
    - name: pipeline-debug
      default: "0"
  results:
    - name: app-name
  workspaces:
    - name: artifacts
      mountPath: /artifacts
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
  steps:
    - name: read-add-name-from-deployment
      image: ibmcom/pipeline-base-image:2.7
      workingDir: "/artifacts"
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail

          if [ $PIPELINE_DEBUG == 1 ]; then
            pwd
            env
            trap env EXIT
            set -x
          fi

          APP=$(yq read "/artifacts/$(params.app-directory)/$(params.deployment-file)" spec.template.metadata.labels.app)

          echo "Found app $APP"

          echo -n "$APP" > $(results.app-name.path)
