---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inventory-promote
spec:
  params:
    - name: source
      description: promotion source
    - name: target
      description: promotion target
    - name: priority
      default: "Critical | High | Moderate | Low | Planning"
    - name: assignee
      default: "_PROVIDE INFORMATION_"
    - name: description
      default: "_PROVIDE INFORMATION_"
    - name: purpose
      default: "_PROVIDE INFORMATION_"
    - name: impact
      default: "_PROVIDE INFORMATION_"
    - name: backout-plan
      default: "_PROVIDE INFORMATION_"
    - name: git-api-token-key
      description: github enterprise api token secret name
      default: "git-token"
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"

  results:
    - name: promotion-pr-url

  workspaces:
    - name: secrets
      mountPath: /secrets

  volumes:
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json

  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
      - name: PIPELINE_RUN_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
  steps:
    - name: inventory-promote
      image: wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/ibm-compliance-automation:1.3.2@sha256:0d1f871a0e91e5963dc16bffbf1723265b2f2e2c3cbe6e0170585f80387e8f08
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
      script: |
        #!/bin/bash
        set -e -o pipefail;

        if [ $PIPELINE_DEBUG == 1 ]; then
          env
          cat /cd-config/toolchain.json
          trap env EXIT
          set -x
        fi

        export GHE_TOKEN=$(cat "/secrets/$(params.git-api-token-key)")
        export INVENTORY_URL=$(jq -r '.services[] | select(.toolchain_binding.name=="inventory-repo")
          | .parameters.repo_url' /cd-config/toolchain.json)

        export GHE_REPO=$(echo "$INVENTORY_URL" | cut -f5 -d/ | cut -f1 -d.)
        export GHE_ORG=$(echo "$INVENTORY_URL" | cut -f4 -d/)

        PROMOTION_PR=$(cocoa inventory promote \
          --source="$(params.source)" \
          --target="$(params.target)" \
          --priority="$(params.priority)" \
          --assigned-to="$(params.assignee)" \
          --description="$(params.description)" \
          --purpose="$(params.purpose)" \
          --impact="$(params.impact)" \
          --backout-plan="$(params.backout-plan)")

        echo -n "${PROMOTION_PR}" | tee $(results.promotion-pr-url.path)
