---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: onepipeline-dockerconfigjson
      description: dockerconfigjson for images used in .one-pipeline.yaml
      default: "eyJhdXRocyI6e319" # ie. {"auths":{}} base64 encoded
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: pipeline-name
      description: The name of the pipeline to run
      default: cd-pipeline
    - name: compliance-baseimage
      description: one-pipeline baseimage to run most of the built-in pipeline code
      default: "wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/compliance-baseimage:2.6.0@sha256:d83bc896af1099e67dcb2e062f35ca9926a1b107ca8723b7383443f6dfbc29f6"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.onepipeline-dockerconfigjson)
      metadata:
        name: onepipeline-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
        - name: onepipeline-pull-secret
      metadata:
        name: sa-pullsecret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: $(params.pipeline-name)
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: compliance-baseimage
            value: $(params.compliance-baseimage)
        serviceAccountName: sa-pullsecret
