---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
    - name: cluster-region
      description: The IBM Cloud Kubernetes cluster region
      default: us-south
    - name: cluster-namespace
      description: The Kubernetes cluster namespace
      default: default
    - name: doi-toolchain-id
      description: toolchain ID
    - name: emergency-label
      description: the name of the emergency label
    - name: servicenow-api-base-url
      description: Base API URL for ServiceNow to handle Change Requests
      default: "https://watsontest.service-now.com"
    - name: change-request-id
      description: ServiceNow Change Request ID
      default: "notAvailable"
    - name: servicenow-configuration-item
      description: ServiceNow registered Configuration Item
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: onepipeline-dockerconfigjson
      description: dockerconfigjson for images used in .one-pipeline.yaml
      default: "eyJhdXRocyI6e319" # ie. {"auths":{}} base64 encoded
    - name: slack-notifications
      description: toggles slack notifications
    - name: cos-bucket-name
      description: Bucket name in your Cloud Object Storage instance, used as an Evidence Locker
      default: ""
    - name: cos-endpoint
      description: Endpoint of your Cloud Object Storage instance, used as an Evidence Locker
      default: ""
    - name: one-pipeline-config
      description: Configuration file to be used to customize pipeline behavior
      default: .one-pipeline.yaml
    - name: one-pipeline-config-branch
      description: The branch where the configuration file is kept
      default: master
    - name: target-environment
      description: target environment, this can be overridden (defaults to prod)
      default: "prod"
    - name: region
      description: target region (optional)
      default: ""
    - name: doi-environment
      description: doi target environment, this can be overridden
      default: ""
    - name: target-environment-ref
      description: target environment branch from git trigger binding
      default: ""
    - name: pipeline-name
      description: The name of the pipeline to run
      default: cd-pipeline
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.onepipeline-dockerconfigjson)
      metadata:
        name: onepipeline-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
        - name: onepipeline-pull-secret
      metadata:
        name: sa-pullsecret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: $(params.pipeline-name)
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: servicenow-api-base-url
            value: $(params.servicenow-api-base-url)
          - name: servicenow-configuration-item
            value: $(params.servicenow-configuration-item)
          - name: cluster
            value: $(params.cluster)
          - name: cluster-region
            value: $(params.cluster-region)
          - name: cluster-namespace
            value: $(params.cluster-namespace)
          - name: doi-toolchain-id
            value: $(params.doi-toolchain-id)
          - name: emergency-label
            value: $(params.emergency-label)
          - name: change-request-id
            value: $(params.change-request-id)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: slack-notifications
            value: $(params.slack-notifications)
          - name: cos-bucket-name
            value: "$(params.cos-bucket-name)"
          - name: cos-endpoint
            value: "$(params.cos-endpoint)"
          - name: one-pipeline-config
            value: $(params.one-pipeline-config)
          - name: one-pipeline-config-branch
            value: $(params.one-pipeline-config-branch)
          - name: target-environment
            value: $(params.target-environment)
          - name: region
            value: $(params.region)
          - name: doi-environment
            value: $(params.doi-environment)
          - name: target-environment-ref
            value: $(params.target-environment-ref)
        serviceAccountName: sa-pullsecret
