---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: ibmcloud-api-key
      description: IBM Cloud API key
    - name: registry-namespace
      description: the ibmcloud registry namespace
    - name: registry-region
      description: the ibmcloud registry region
      default: us-south
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
    - name: cluster-region
      description: The IBM Cloud Kubernetes cluster region
      default: us-south
    - name: cluster-namespace
      description: The Kubernetes cluster namespace
      default: default
    - name: incident-issues-url
      description: Incident issues repo url
    - name: evidence-locker-url
      description: Evidence locker repo url
    - name: emergency-label
      description: the name of the emergency label
    - name: application
      description: name of the deployed app or service
    - name: servicenow-api-token
      description: API token for ServiceNow to handle Change Requests
    - name: servicenow-api-url
      description: API URL for ServiceNow to handle Change Requests
      default: "https://watsontest.service-now.com/api/ibmwc/change"
    - name: change-request-id
      description: ServiceNow Change Request ID
      default: "notAvailable"
    - name: servicenow-configuration-item
      description: ServiceNow registered Configuration Item

  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: cd-pipeline
        params:
          - name: pipeline-pvc
            value: pipelinerun-$(uid)-pvc
          - name: revision
            value: $(params.revision)
          - name: repository
            value: $(params.repository)
          - name: ibmcloud-api-key
            value: $(params.ibmcloud-api-key)
          - name: servicenow-api-token
            value: $(params.servicenow-api-token)
          - name: servicenow-api-url
            value: $(params.servicenow-api-url)
          - name: servicenow-configuration-item
            value: $(params.servicenow-configuration-item)
          - name: cluster
            value: $(params.cluster)
          - name: cluster-region
            value: $(params.cluster-region)
          - name: cluster-namespace
            value: $(params.cluster-namespace)
          - name: application
            value: $(params.application)
          - name: emergency-label
            value: $(params.emergency-label)
          - name: evidence-locker-url
            value: $(params.evidence-locker-url)
          - name: pipeline-run-id
            value: $(params.pipeline-run-id)
          - name: image
            value: $(params.image)
          - name: change-request-id
            value: $(params.change-request-id)
