---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
    - name: cluster-region
      description: The IBM Cloud Kubernetes cluster region
      default: us-south
    - name: cluster-namespace
      description: The Kubernetes cluster namespace
      default: default
    - name: doi-toolchain-id
      description: toolchain ID
    - name: evidence-locker-url
      description: Evidence locker repo url
    - name: incident-issues-url
      description: Incident issues repo url
    - name: inventory-url
      description: Inventory repo url
    - name: emergency-label
      description: the name of the emergency label
    - name: application
      description: name of the deployed app or service
    - name: servicenow-api-base-url
      description: Base API URL for ServiceNow to handle Change Requests
      default: "https://watsontest.service-now.com"
    - name: change-request-id
      description: ServiceNow Change Request ID
      default: "notAvailable"
    - name: servicenow-configuration-item
      description: ServiceNow registered Configuration Item
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: slack-notifications
      description: toggles slack notifications
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
      metadata:
        name: sa-pullsecret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: cd-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: revision
            value: $(params.revision)
          - name: repository
            value: $(params.repository)
          - name: servicenow-api-base-url
            value: $(params.servicenow-api-base-url)
          - name: servicenow-configuration-item
            value: $(params.servicenow-configuration-item)
          - name: cluster
            value: $(params.cluster)
          - name: cluster-region
            value: $(params.cluster-region)
          - name: cluster-namespace
            value: $(params.cluster-namespace)
          - name: doi-toolchain-id
            value: $(params.doi-toolchain-id)
          - name: application
            value: $(params.application)
          - name: emergency-label
            value: $(params.emergency-label)
          - name: evidence-locker-url
            value: $(params.evidence-locker-url)
          - name: incident-issues-url
            value: $(params.incident-issues-url)
          - name: inventory-url
            value: $(params.inventory-url)
          - name: change-request-id
            value: $(params.change-request-id)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: slack-notifications
            value: $(params.slack-notifications)
        serviceAccountName: sa-pullsecret
